### ISSUE TITLE
Bundle size is huge: 124.7kb

### ISSUE THREAD

**Issue by mortargrind** [pichillilorenzo/jackson-js#2]
See: https://bundlephobia.com/result?p=jackson-js@1.0.0

125kb for JSON serializing/deserializing is unacceptable for almost every frontend project I can think of. I didn't check the contents of the bundle nor the whole codebase but I guess there's something wrong with your bundling process and it includes some unrelated stuff into the bundle. FYI.

**Comment by pichillilorenzo** [comment]
Yes, I need to remove `dayjs` dependency from the bundle and make it required if someone needs to use`@JsonFormat()` for Dates.

**Comment by pichillilorenzo** [comment]
Updated with new version `1.1.0`. The bundle size is half of the previous one!
Now, the `meriyah` (https://github.com/meriyah/meriyah) dependency is the heaviest dependency but it is required and cannot be removed from this library.
