### ISSUE TITLE
(angular) Unable to serialize Date with JsonFormatShape.STRING

### ISSUE THREAD

**Issue by gbrugiere** [pichillilorenzo/jackson-js#4]
*Disclaimer : please excuse me if this is not the good way to submit this problem*

## Environment

**Angular version:**
9 (compiler 9.1.9)

## Description

**Expected behavior:** 
Correct serialisation of Date field

**Current behavior:** 
Error in console :
`ERROR Error: No date library has been set. To be able to use @JsonFormat() on class properties of type "Date" with JsonFormatShape.STRING, a date library needs to be set. Date libraries supported: "https://github.com/moment/moment", "https://github.com/iamkun/dayjs/".`

## Steps to reproduce

1. Create an Angular project (i.e. with stackblitz) then add dependencies in package.json
```
...
    "dayjs": "^1.8.28", <-- added for try but it's doesn't work
    "jackson-js": "^1.1.0",
    "moment": "^2.27.0",
...
```

2. Create an entity with a Date field like : 
```
export class User {
  
  @JsonProperty()
  @JsonClassType({type: () => [Date]})
  @JsonFormat({
    shape: JsonFormatShape.STRING,
    pattern: 'YYYY-MM-DD hh:mm:ss',
  })
  birthdate:Date;
}
```

3. Then instanciate class, fill it and try to serialize
```
    let  user=new User();
    user.birthdate=new Date();

    let om = new ObjectMapper(); 
    let stringifiedUser = om.stringify<User>(user);
```

The console shows the error given higher.

I may add that I've tried `import * as moment from 'moment';` without success.

Is there something I'm missing in configuration ? I haven't seen anything in the documentation. 

Keep the good work, it's about to save my day (well, week I should say :) ): your library really rocks.

**Comment by pichillilorenzo** [comment]
You need to set the date library option. An example could be found inside the `tests` folder, here:
https://github.com/pichillilorenzo/jackson-js/blob/adb7bd31b5fcf006665e4947dd3b6ef4ea468b57/tests/JsonFormat.ts#L70

```javascript
const moment = require('moment');

// your code

const objectMapper = new ObjectMapper();

const jsonData = objectMapper.stringify<User>(user, {
  dateLibrary: moment
});
```

Thanks for the support!
